#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'net/http'
require 'uri'
require 'yaml'

CONFIG_PATH = '_config.yml'
PUBLICATIONS_PATH = '_data/publications.yml'
OPENALEX_URL = 'https://api.openalex.org/works'

def load_yaml(path)
  return {} unless File.exist?(path)

  YAML.safe_load(File.read(path), permitted_classes: [], aliases: false) || {}
end

def fetch_openalex_works(orcid)
  query_orcid = orcid.start_with?('http') ? orcid : "https://orcid.org/#{orcid}"
  uri = URI(OPENALEX_URL)
  params = {
    'filter' => "author.orcid:#{query_orcid}",
    'sort' => 'publication_date:desc',
    'per-page' => '200'
  }
  uri.query = URI.encode_www_form(params)

  req = Net::HTTP::Get.new(uri)
  req['User-Agent'] = 'andrew-balmer-site-publication-updater/1.0'

  res = Net::HTTP.start(uri.host, uri.port, use_ssl: true) { |http| http.request(req) }
  raise "OpenAlex request failed: #{res.code} #{res.message}" unless res.is_a?(Net::HTTPSuccess)

  body = JSON.parse(res.body)
  body.fetch('results', [])
end

def clean_doi(doi)
  return '' if doi.nil? || doi.empty?

  doi.sub(%r{^https?://(dx\.)?doi\.org/}i, '')
end

def author_string(authorships, highlight_substring)
  return '' unless authorships.is_a?(Array)

  names = authorships.map { |a| a.dig('author', 'display_name') }.compact
  names.map do |name|
    if !highlight_substring.empty? && name.downcase.include?(highlight_substring.downcase)
      "**#{name}**"
    else
      name
    end
  end.join(', ')
end

def to_publication_entry(work, highlight_substring)
  doi = clean_doi(work['doi'].to_s)
  first_page = work.dig('biblio', 'first_page').to_s
  last_page = work.dig('biblio', 'last_page').to_s
  pages = if !first_page.empty? && !last_page.empty?
            "#{first_page}-#{last_page}"
          else
            first_page
          end

  {
    'title' => work['display_name'].to_s,
    'authors' => author_string(work['authorships'], highlight_substring),
    'journal' => work.dig('primary_location', 'source', 'display_name').to_s,
    'year' => work['publication_year'].to_i,
    'volume' => work.dig('biblio', 'volume').to_s,
    'pages' => pages.to_s,
    'doi' => doi,
    'preprint_doi' => '',
    'paper_url' => work.dig('primary_location', 'landing_page_url').to_s,
    'pdf_url' => work.dig('open_access', 'oa_url').to_s,
    'code_url' => '',
    'featured' => false,
    'tags' => []
  }
end

def merge_with_existing(new_entries, existing_entries)
  existing_by_doi = {}
  existing_by_title_year = {}

  existing_entries.each do |entry|
    doi = entry['doi'].to_s
    existing_by_doi[doi] = entry unless doi.empty?

    title = entry['title'].to_s.strip
    year = entry['year'].to_s.strip
    next if title.empty? || year.empty?

    existing_by_title_year["#{title}|#{year}"] = entry
  end

  new_entries.each do |entry|
    previous = nil

    doi = entry['doi'].to_s
    previous = existing_by_doi[doi] unless doi.empty?

    if previous.nil?
      title = entry['title'].to_s.strip
      year = entry['year'].to_s.strip
      previous = existing_by_title_year["#{title}|#{year}"] unless title.empty? || year.empty?
    end

    next if previous.nil?

    previous.each do |field, value|
      next if value.nil?
      next if value.respond_to?(:empty?) && value.empty?

      entry[field] = value
    end
  end

  merged_keys = new_entries.map { |entry| "#{entry['title']}|#{entry['year']}" }.to_h { |key| [key, true] }

  existing_entries.each do |entry|
    key = "#{entry['title']}|#{entry['year']}"
    next if merged_keys[key]

    new_entries << entry
  end

  new_entries
end

def write_yaml(path, entries)
  header = <<~HEADER
    # Auto-generated by scripts/update_publications.rb
    # Source: OpenAlex by ORCID (set author.orcid in _config.yml)
    # Manual edits in _data/publications.yml take precedence where a title/year
    # match exists, so curated paper/code links are preserved across refreshes.
  HEADER

  File.write(path, header + entries.to_yaml)
end

config = load_yaml(CONFIG_PATH)
orcid = config.dig('author', 'orcid').to_s.strip
highlight_name = ENV.fetch('PUBLICATIONS_HIGHLIGHT_NAME', 'Balmer').strip

if orcid.empty?
  warn 'Skipping update: author.orcid is empty in _config.yml'
  exit 0
end

existing_publications = load_yaml(PUBLICATIONS_PATH)
existing_publications = [] unless existing_publications.is_a?(Array)

works = fetch_openalex_works(orcid)
entries = works.map { |w| to_publication_entry(w, highlight_name) }
entries.select! { |e| !e['title'].empty? && e['year'] > 0 }

# Keep most recent unique title+year pair.
seen = {}
entries = entries.select do |entry|
  key = "#{entry['title']}|#{entry['year']}"
  next false if seen[key]

  seen[key] = true
  true
end

entries.sort_by! { |e| [-e['year'].to_i, e['title']] }
entries = merge_with_existing(entries, existing_publications)

write_yaml(PUBLICATIONS_PATH, entries)
puts "Updated #{PUBLICATIONS_PATH} with #{entries.size} publication(s)."
